# Generated by Django 4.2.3 on 2023-08-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_team',
            new_name='table2',
        ),
    ]
