# Generated by Django 4.2.3 on 2023-08-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_rename_table_team_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table2',
        ),
    ]
