# Generated by Django 4.2.3 on 2023-08-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel1app', '0002_table_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_team',
        ),
    ]
